[package]
name = "super-oxi-car"
version = "0.1.0"
edition = "2021"
authors = ["nicolas cesar sabbatini vrech"]

[dependencies]
bevy = "0.12"
bevy_turborand = "0.7"
interpolation = "0.3"

[profile.dev.package."*"]
opt-level = 3
